LYNX-152: Documentation for attributesMetadata query
AdobeDocs/commerce-webapi pull request #127
Opened 2023-04-20 13:47 UTC by eliseacornejo

## Purpose of this pull request

This pull request (PR) ...

## Affected pages

- ...

## Links to Magento Open Source code

- ...

2023-04-20 20:54 UTC, keharper commented
@eliseacornejo It will take a few days to get to this PR. 

I know that a version of this query was packaged with PWA and is documented at https://developer.adobe.com/commerce/webapi/graphql/schema/store/queries/attributes-metadata/

We need to find a way to differentiate these two identically named queries, and provide guidance for anyone who has already installed it.

Also, I placed the original `attributesMetadata` under Schema > Store , because I was trying to avoid creating numerous areas under Schema that each have only one or two queries/mutations. Can this query be moved to the same query as the old version?

2023-04-20 20:57 UTC, keharper commented
Maybe this query needs to be renamed to `attributesMetadataV2`.

2023-04-21 12:49 UTC, eliseacornejo commented
@keharper Yes, you are right, we are going to rename this query.  So I will be updating this PR, after having this. Also I would deprecate the other one in PWA, so we need to add something on that query that it is deprecated. 
For the placement, I don't think the best place is to be under store as it is not a query totally related to store, this is a query that can retrieve attributes for different entities like catalog_product, customer, customer_address, this is why we created a new area.

2023-04-26 19:07 UTC, keharper requested changes
Please back out changes to the `static/graphql-api/index.html` file. We have automation that will generate this file when we're ready to publish the autogenerated schema docs.

2023-04-26 22:26 UTC, keharper reviewed
@eliseacornejo I talked to Cris Partica about the placement of the new query. This query and the form query isn't limited to EAV. Instead, please create a `attributes` directory, and move the file there. Also, update the left navigation from Eav to Attributes. 

I'm going to move the deprecated queries immediately after merging this PR.

2023-04-27 15:16 UTC, keharper commented on src/pages/graphql/schema/attributes/queries/custom-attribute-metadata-v2.md
> +Some of the differences of this new query are:
```suggestion
This new query has several features that were not available in the deprecated queries:

```
(Add a blank line after the colon)

2023-04-27 15:16 UTC, keharper commented on src/pages/graphql/schema/attributes/queries/custom-attribute-metadata-v2.md
> +- Can be extended by all entity types.
```suggestion
-  All entity types can extend this query.
```

2023-04-27 15:16 UTC, keharper commented on src/pages/graphql/schema/attributes/queries/custom-attribute-metadata-v2.md
> +- This provides access to all properties of eav attributes.
```suggestion
-  The query provides access to all properties of EAV attributes.
```

2023-04-27 15:16 UTC, keharper commented on src/pages/graphql/schema/attributes/queries/custom-attribute-metadata-v2.md
> +- It introduced uid information for the attributes.
```suggestion
-   `uid` values are now available.

```

Add a blank line after the last bullet. Also make sure there are no blank spaces at the end any of the lines.

2023-04-28 15:35 UTC, merged