ACPT-674: ImportCsvApi Docs
AdobeDocs/commerce-webapi pull request #28
Opened 2022-08-02 01:29 UTC by aakashk994

## Purpose of this pull request

This pull request (PR) ...

## Affected pages

-  ...

## Links to related PRs or Jira tickets

-  ...

## Checklist:

-  [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
-  [ ] My changes follow the code style of this project.
-  [ ] I have read the **CONTRIBUTING** document.
-  [ ] All new and existing tests passed.

2022-08-02 16:32 UTC, aakashk994 commented
@keharper can you review this PR? I don't have permissions to assign reviewers in this repository.

2022-08-02 23:58 UTC, keharper requested changes
Your introduction section needs to mention that the data to be uploaded needs to be in CSV format. You might need to describe what data/columns are expected for each entity type. Check the merchant documentation at and near https://docs.magento.com/user-guide/system/data-csv.html  Don't copy/paste too much. Cross reference as much as you can.

If the possible behaviors aren't the same for each entity, then they'll have to be mapped in the introduction as well.

You also need to address error handling. 

Also, add a link to the new topic in `src/data/navigation/sections/rest.js`.

2022-08-02 23:58 UTC, keharper commented on src/pages/rest/modules/import/index.md
> +
Use the entity names instead of the UI labels.

2022-08-02 23:58 UTC, keharper commented on src/pages/rest/modules/import/index.md
> +POST /rest/default/V1/import/csv
Same comment about the route.

2022-08-02 23:58 UTC, keharper commented on src/pages/rest/modules/import/index.md
> +|`entity`|Type of entity to be imported| string | Required for determining type of entity being imported|
```suggestion
|`entity` | The type of entity to be imported| string | Required. One of .... |
```

2022-08-02 23:58 UTC, keharper commented on src/pages/rest/modules/import/index.md
> +|`behavior` | Import Behavior | string | Required for determining if entities are being added/updated,replaced or deleted |
```suggestion
|`behavior` | The action  to perform | string | Required. One of .... |
```

2022-08-02 23:58 UTC, keharper commented on src/pages/rest/modules/import/index.md
> +|`validationStrategy` | Strategy to use when entities are invalid | string | Required for determining validation strategy|
```suggestion
|`validationStrategy` | Strategy to use when entities are invalid | string | Required. One of ....|
```

This needs to be discussed in the description of the endpoint.

2022-08-02 23:58 UTC, keharper commented on src/pages/rest/modules/import/index.md
> +|`allowedErrorCount` | No. of errors before import is canceled | string | Required for canceling import after certain number of invalid rows|
```suggestion
|`allowedErrorCount` | The maximum number of errors that can occur until import is canceled | string | Required |
```

What happens with the uploads that did not encounter errors before the error count is reached? Are they marked as successful, or are they rolled back?

2022-08-02 23:58 UTC, keharper commented on src/pages/rest/modules/import/index.md
> +|`csvData` | Base64 encoded string containing csv data | string | Csv data is encoded in base64 format|
```suggestion
|`csvData` | Base64 encoded string containing CSV data | string | Required |
```

2022-08-02 23:58 UTC, keharper commented on src/pages/rest/modules/import/index.md
> +<CodeBlock slots="heading, code" repeat="2" languages="JSON, JSON" />
Delete this line

2022-08-02 23:58 UTC, keharper commented on src/pages/rest/modules/import/index.md
> +#### Response
```suggestion
**Response:**
```

2022-08-10 05:46 UTC, keharper requested changes
@aakashk994 I've made numerous edits to this PR. Please pull these changes in locally and begin addressing the comments I left.

This is an important and powerful endpoint, so we need to fully consider what can go wrong. I can envision so many problems with the source data, so we need to describe the proper construction of the CSV file/input so that the reader can avoid these errors. And if they occur any errors, how to debug them.

Note that I'm not assuming that the source data is a CSV file. I can imagine some CRM software exporting customer data in a GraphQL query, some middleware transforming that  output into rows of CVS data, then encoding it in b64, all without writing to a file. So we can't just copy the merchant documentation. We need to cherry pick the most important parts.

2022-09-15 13:52 UTC, hguthrie commented
@keharper Do you have time for a follow-up review?

2022-11-03 16:00 UTC, keharper approved these changes

2022-11-03 16:46 UTC, merged

2022-12-20 20:17 UTC, jeff-matthews commented on src/pages/rest/modules/import/index.md
> +
@keharper, will you please add an H1 for this?