[Documentation] Update documentation regarding ReCaptcha in graphQL and REST requests
AdobeDocs/commerce-webapi pull request #283
Opened 2024-02-21 05:44 UTC by vkolesny

## Purpose of this pull request

This pull request (PR) is a continuation of the https://github.com/magento-commerce/devdocs/pull/3042 Pull Request.
We should provide more clarity that "X-Captcha" and "X-ReCaptcha" headers can be generated by web form widgets in the background only.
Please provide more clear explanation regarding X-Captcha and X-ReCaptcha headers. Please add to the documentation examples how this headers can be added to the requests.

## Affected pages

- https://developer.adobe.com/commerce/webapi/graphql/usage/protected-mutations/
- https://developer.adobe.com/commerce/webapi/rest/use-rest/protected-endpoints/

2024-02-21 15:21 UTC, keharper commented
@vkolesny Are the changes in the PR due to changes in the 2.4.7 release, or are they describing released code?

2024-02-21 16:08 UTC, vkolesny commented
Hi @keharper ,
These changes are for already existing code.

It is just to add more clarity and explanation to already existing feature.

2024-02-21 16:47 UTC, keharper requested changes

2024-02-21 16:47 UTC, keharper commented on src/pages/graphql/usage/protected-mutations.md
> +If CAPTCHA or reCAPTCHA is enabled on pages requiring shopper input, then in most cases, the corresponding mutations that send requests to the application server must include an HTTP header that cont
```suggestion
If CAPTCHA or reCAPTCHA is enabled on pages requiring shopper input, then in most cases, the corresponding mutations that send requests to the application server must include an HTTP header that contains a value entered by the shopper (for CAPTCHA) or generated by the Google API (for reCAPTCHA). These headers are generated by UI Web form widgets during interactions with the shopper. However, if you specify an integration authorization token in the header of the mutation, then you do not supply a header specific to CAPTCHA or reCAPTCHA.
```

2024-02-21 16:47 UTC, keharper commented on src/pages/graphql/usage/protected-mutations.md
> +Even when Adobe Commerce is used in a headless way, like with PWA, the Merchant must have their own Web UI which must include rendering the correct Captcha or reCAPTCHA web form widget, to capture th
```suggestion
Even when Adobe Commerce is used in a headless way, like with PWA, the merchant must have their own Web UI that renders the correct Captcha or reCAPTCHA web form widget, captures the proper `X-Captcha` or `X-ReCaptcha` HTTP header, and sends it in the API request in the background only.
```

2024-02-21 16:47 UTC, keharper commented on src/pages/rest/use-rest/protected-endpoints.md
> +If CAPTCHA or reCAPTCHA is enabled on pages requiring shopper input, then in most cases, the corresponding endpoints that send requests to the Adobe Commerce server must include an HTTP header that c
```suggestion
If CAPTCHA or reCAPTCHA is enabled on pages requiring shopper input, then in most cases, the corresponding endpoints that send requests to the Adobe Commerce server must include an HTTP header that contains a value entered by the shopper (for CAPTCHA) or generated by the Google API (for reCAPTCHA). These headers are generated by UI Web form widgets during interactions with the shopper. However, if you specify an integration authorization token in the header of the endpoint, then you do not supply a header specific to CAPTCHA or reCAPTCHA.
```

2024-02-21 16:47 UTC, keharper commented on src/pages/rest/use-rest/protected-endpoints.md
> +Even when Adobe Commerce is used in a headless way, like with PWA, the Merchant must have their own Web UI which must include rendering the correct Captcha or reCAPTCHA web form widget, to capture th
```suggestion
Even when Adobe Commerce is used in a headless way, like with PWA, the merchant must have their own Web UI that renders the correct Captcha or reCAPTCHA web form widget, captures the proper `X-Captcha` or `X-ReCaptcha` HTTP header, and sends it in the API request in the background only.
```

2024-02-21 16:51 UTC, keharper commented
@vkolesny This PR is failing validation checks because external links in unrelated topics are suddenly breaking. I fixed those broken links in another PR. If you're using the GH web UI to incorporate my comments, click **Update branch**.  Otherwise, pull in the latest changes from `main`.

2024-02-21 21:55 UTC, vkolesny commented
Thanks, @keharper.
Proposed changes were committed.
Latest main was pulled into PR.

2024-02-22 03:45 UTC, keharper approved these changes

2024-02-22 03:45 UTC, merged