LYNX-374: Added new confirm-email mutation
AdobeDocs/commerce-webapi pull request #286
Opened 2024-03-08 14:07 UTC by svera

## Purpose of this pull request

This pull request (PR) adds a new page with information about the new `confirmEmail` GraphQl mutation

## Affected pages

- ...

2024-03-08 15:48 UTC, keharper requested changes
Also, add a link to the new mutation in src/pages/graphql/schema/customer/mutations/index.md

2024-03-08 15:48 UTC, keharper commented on src/pages/graphql/schema/customer/mutations/confirm-email.md
> +
Please add the following lines before the head1. 

import BetaNote from '/src/_includes/graphql/notes/beta.md'

<BetaNote />

2024-03-08 15:48 UTC, keharper commented on src/pages/graphql/schema/customer/mutations/confirm-email.md
> +Use the `confirmEmail` mutation to confirm the email address of a customer.
```suggestion
The `confirmEmail` mutation completes the customer activation process by confirming validity of a customer's email address. Adobe Commerce sends a confirmation key to the customer when they request to create an account. The customer must supply this confirmation key.
```

2024-03-08 15:48 UTC, keharper commented on src/pages/graphql/schema/customer/mutations/confirm-email.md
> +
Add the following lines below the syntax. I will have to go back and a link to the reference once we've generated it.

```
## Reference

The `confirmEmail` reference provides detailed information about the types and fields defined in this query.
```

2024-03-08 15:48 UTC, keharper commented on src/pages/graphql/schema/customer/mutations/confirm-email.md
> +
Also add the following heading before the example

```
## Example usage
```

2024-03-08 15:48 UTC, keharper commented on src/pages/graphql/schema/customer/mutations/confirm-email.md
> +## Input attributes
Delete this section. Since we now have autogenerated reference docs, we no longer document the fields and types.

2024-03-08 15:48 UTC, keharper commented on src/pages/_includes/graphql/confirm-email-input.md
> +### ConfirmEmailInput attributes
Delete this file.

2024-03-08 15:48 UTC, keharper commented on src/pages/graphql/schema/customer/mutations/confirm-email.md
> +The following call confirms `roni_cost@example.com` as the email address of the customer by using the confirmation key `abcde` that should have been received by the customer in his / her email inbox.
```suggestion
The following call confirms `roni_cost@example.com` as the email address of the customer by using the confirmation key `abcde`.
```

2024-03-11 10:05 UTC, svera commented
> Also, add a link to the new mutation in src/pages/graphql/schema/customer/mutations/index.md

@keharper this page is currently empty, are we sure we want to add the link there? and which format should that link have in case we need to add it there?

2024-03-11 16:13 UTC, keharper commented
@svera It's been a long time since the `2.4.7-develop` branch had been synced with `main`. Please pull in the changes, and you'll see that the index file now has content.

2024-03-22 15:11 UTC, keharper approved these changes

2024-03-22 15:18 UTC, merged