ACP2E-2872: [Documentation] Update documentation regarding Bundle pro…
AdobeDocs/commerce-webapi pull request #307
Opened 2024-03-21 18:19 UTC by arnobsh

## Purpose of this pull request

This pull request (PR)  the documentation update for [ACP2E-2797](https://jira.corp.adobe.com/browse/ACP2E-2797). The Jira ticket link for documentation update is https://jira.corp.adobe.com/browse/ACP2E-2872

## Affected pages

## Links to Magento Open Source code

2024-03-21 18:20 UTC, arnobsh commented
@magento run all tests

2024-03-21 22:22 UTC, jhadobe requested changes

2024-03-21 22:22 UTC, jhadobe commented on src/pages/rest/modules/bundle/index.md
> +## Retrieve store specific bundle product details
```suggestion
## Retrieve store-specific bundle product details
```

2024-03-21 22:22 UTC, jhadobe commented on src/pages/rest/modules/bundle/index.md
> +bundle product details add `store_code` at API request. Like this `GET {store_code}/V1/products/{sku}`
```suggestion
The following example retrieves store-specific bundle product details for a multi-store configuration by using the `GET V1/products/{sku}` call. For store specific
bundle product details add the `store_code` to the API request. For example, `GET {store_code}/V1/products/{sku}`
```

2024-03-21 22:22 UTC, jhadobe commented on src/pages/rest/modules/bundle/index.md
> +We can get `option_id` from bundle product options from  the response and use the `option_id` to update bundle product option.
```suggestion

Retrieve the `option_id` from the bundle product options section of the response and use it to update the bundle product option.
```

Can you clarify what is being updated here and why.

2024-03-21 22:22 UTC, jhadobe commented on src/pages/rest/modules/bundle/index.md
> +
```suggestion
## Update store-specific bundle product options

The following example uses the `PUT /V1/bundle-products/options/{optionId}` call to update the bundle product option. For a store-specific request, add the `store_code`. For example, `PUT {store_code}/V1/bundle-products/options/{optionId}`

```

2024-03-21 22:22 UTC, jhadobe commented on src/pages/rest/modules/bundle/index.md
> +The following example update bundle product option:
```suggestion
The following example updates the bundle product option:
```

2024-03-21 22:22 UTC, jhadobe commented on src/pages/rest/modules/bundle/index.md
> +
```suggestion
## Update store-specific bundle product option links

The following example uses the `PUT /V1/bundle-products/{sku}/links/{optionId}` call to update the bundle product option link. For a store-specific call, add `store_code` to the API request. For example, `PUT {store_code}/V1/bundle-products/{sku}/links/{optionId}`

```

2024-03-21 22:22 UTC, jhadobe commented on src/pages/rest/modules/bundle/index.md
> +The following example update bundle product option link:
```suggestion
The following example updates the bundle product option link:
```

2024-03-21 22:22 UTC, jhadobe commented on src/pages/rest/modules/bundle/index.md
> +```
```suggestion
```

```

2024-03-22 15:41 UTC, arnobsh commented
@magento run all tests

2024-03-22 16:44 UTC, jhadobe commented
looks good to me. @keharper any thoughts?

2024-03-25 22:03 UTC, keharper commented
@arnobsh This new topic should be step 4 of the bundle product tutorial under `rest/tutorials/bundle-product`. 

The intro paragraph should state that the actions shown below modify the bundle product in a single store instead of all stores, and that it is optional.

The first ordered list item should be the GET call. Instruct the reader to note the important fields that will be used in the subsequent items.

Then, with second and third ordered list items, show how to change the product details and options.

Remove the changes in `src/pages/rest/modules/index.md`.

Add navigation to the new topic in `src/data/navigation/sections/rest.js`, below line 406

2024-03-26 13:48 UTC, arnobsh commented
> @arnobsh This new topic should be step 4 of the bundle product tutorial under `rest/tutorials/bundle-product`.
> 
> The intro paragraph should state that the actions shown below modify the bundle product in a single store instead of all stores, and that it is optional.
> 
> The first ordered list item should be the GET call. Instruct the reader to note the important fields that will be used in the subsequent items.
> 
> Then, with second and third ordered list items, show how to change the product details and options.
> 
> Remove the changes in `src/pages/rest/modules/index.md`.
> 
> Add navigation to the new topic in `src/data/navigation/sections/rest.js`, below line 406

Ok, Thank you. Working on it

2024-04-01 17:13 UTC, arnobsh commented
@magento run all tests

2024-04-01 17:15 UTC, arnobsh commented
@keharper can you please have a review on updated changes? Thanks

2024-04-03 19:05 UTC, keharper commented
@arnobsh I meant one new topic with three steps

1.  Get bundle product details
2. Update bundle product options
3. Update bundle product links

I looked at the example for updating options, and it seems the call is updating the quantities of the two products from 1 to 10 and 12, respectively. Would it make more sense to change the prices? I don't understand why the quantities would change that drastically.

Also, you mention  retrieving the `selection_id` from the bundle product option `product_links` section, but it doesn't appear in the GET response, as far as I can tell.

2024-04-24 19:50 UTC, arnobsh commented
@magento run all tests

2024-04-24 19:51 UTC, arnobsh commented
> @arnobsh I meant one new topic with three steps
> 
> 1. Get bundle product details
> 2. Update bundle product options
> 3. Update bundle product links
> 
> I looked at the example for updating options, and it seems the call is updating the quantities of the two products from 1 to 10 and 12, respectively. Would it make more sense to change the prices? I don't understand why the quantities would change that drastically.
> 
> Also, you mention retrieving the `selection_id` from the bundle product option `product_links` section, but it doesn't appear in the GET response, as far as I can tell.

Updated the documents according to the review. Can you please review again and check if anything needs to be updated/changed? Thanks

2024-04-29 16:20 UTC, keharper approved these changes

2024-04-29 19:27 UTC, merged