ACPT-858: Add gzip info to Documentation for Import API
AdobeDocs/commerce-webapi pull request #54
Opened 2022-11-09 21:45 UTC by JacobBrownAustin

## Description
In  [ACPT-674](https://jira.corp.adobe.com/browse/ACPT-674) , Devdocs was updated with info on new REST endpoint for Import.

Now,  we need to add information about optional gzip compression for the CSV data.

## Related Issue
https://jira.corp.adobe.com/browse/ACPT-858

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-11-09 21:47 UTC, JacobBrownAustin commented on src/pages/rest/modules/import/index.md
> +Before encoding the data in base64,  you can optionally use gzip compression to compress your data.  This is useful when importing large CSV files that may otherwise run into HTTP request size limita
Maybe I should have just said "gzip" instead of "gzip compression" since its redundant,  but not sure if everyone knows about gzip.

2022-11-09 22:14 UTC, jhadobe requested changes

2022-12-05 17:29 UTC, jhadobe approved these changes

2022-12-05 18:09 UTC, keharper approved these changes

2023-01-18 20:53 UTC, merged